spring:
  datasource:
    url: jdbc/mysql:localhost:3306/drugs
    name: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080

mybatis:
  #mapper.xml存放路径（resource）
  mapper-locations: classpath:mapper/*.xml
  #mapper接口文件存放路径
  type-aliases-package: com.durgs.dao
